name: serviguia-api

services:
  server:
    build:
      context: ..
      dockerfile: server/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ../server
          target: /app
          ignore:
            - __pycache__/
            - "*.pyc"
            - .venv/
        - action: rebuild
          path: ../server/requirements.txt
        - action: rebuild
          path: ../server/Dockerfile
  client:
    build:
      context: ..
      dockerfile: client/Dockerfile
    env_file:
      - ../.env
    ports:
      - "5173:5173"
    depends_on:
      - server
    develop:
      watch:
        - action: sync
          path: ../client
          target: /app
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ../client/package.json
        - action: rebuild
          path: ../client/package-lock.json
        - action: rebuild
          path: ../client/Dockerfile
